version: '2.3'

services:
  github-runner-CICD_Example:
    build:
      context: .
    image: github-runner:0.0.1
    environment:
      APP_NAME: "CICD_Example"
      ACTIONS_INSTALLER_URL: "https://github.com/actions/runner/releases/download/v2.277.1/actions-runner-linux-x64-2.277.1.tar.gz"
      GIT_REPO_URL: "https://github.com/SiemensIndustrialEdgeITA/CI_CD_GitHubActions_ExampleApp"
      GIT_RUNNER_TOKEN: "AIGDZWT2PDQ47Y4PTLFQVF3ATESBI"
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './runner-CICD_Example:/tmp/runner'

